name: Hello World

on:
  push:
    branches:
      - main

jobs:
  test_workflow:
    runs-on: ubuntu-20.04
    steps:
      - name: Say Hello
        run: |
          echo "Hello World!"
